### PR TITLE
New Navbar 

### PR DESCRIPTION
**Pull request by monccciii**

### CODE REVIEW

**Comment by tanerdurmaz** [comment]
good effort :clap: 
lets add buttons for [Interns DAO](https://osfd-frontend.vercel.app/internsDAO) & [Team Nouns DAO](https://osfd-frontend-9du3dnnod-adventure.vercel.app/teamnouns) and link pages for both dao. 

Instead of black background lets use current header background. Instead of home button lets use osfd button 
image

**Comment by monccciii** [comment]
Alright, so should I simply just make the background image of the navbar the header image? I thought it would match with the header and look bad.

**Comment by tanerdurmaz** [comment]
> 

we will replace/merge header with navbar

**Comment by monccciii** [comment]
Can I send you designs on Discord? I'm not sure how to design that

**Pull request closed without merging**
