### PR TITLE
Get started page

### PR DESCRIPTION
**Pull request by squal1**
I just did some basic styling and stuff. Would the detailed instructions be provided or should I just come up with the instructions by myself? Also it would be great if there is a design for it so that I can try my best to follow especially in color wise.

Untitled

### CODE REVIEW

**Comment by tanerdurmaz** [comment]
your design looks fine for first pass lets focus on functionality, If we have functional onboarding page with checkboxes we can request a design from penji. 
If we request it now they will probably will not understand what we are looking for.

**Review by tanerdurmaz — COMMENTED** [review]
added my review in prev comment

**Comment by squal1** [comment]
For a get started page I think users should be able to navigate themselves but I still added the check boxes and the page will automatically scroll to the next step when the previous step is checked. Let me know if you want any further changes.
Untitled

**Review by tanerdurmaz — APPROVED** [review]
Looking good for v1, gj :tada:

**Pull request merged**
