### PR TITLE
Metamask button component

### PR DESCRIPTION
**Pull request by BrandonC123**
Task:
- create metamask component which on click will sign in users using "useWeb3React" and store the state in global context
- global states will be const { active, activate, account, library } = useWeb3React();

### CODE REVIEW

**Comment by BrandonC123** [comment]
A few parts of the code were causing typescript errors, did my best to refactor. Also added toast notification when wallet is successfully connected.

**Comment by tanerdurmaz** [comment]
when we refresh page metamask button reappears again even though we already logged in, 

also lets show wallet address and balance if user logged in via metamask.

**Review by tanerdurmaz — COMMENTED** [review]
added my review in prev comment. also you can use :any and ts ignore if ts becomes annoying

**Comment by BrandonC123** [comment]
Picture for reference:
image

**Comment by BrandonC123** [comment]
Quick update, noticed connect metamask button was still displaying briefly while account details are loaded in after refresh. Added loading variable to display when state is available.

**Comment by tanerdurmaz** [comment]
good job :tada: 
lets remove wallet connected popup because it pops up again when we navigate between pages, 
lets update balance after mint

**Pull request merged**
