### PR TITLE
Created component to display a log of minted addresses.

### PR DESCRIPTION
**Pull request by squal1**
The component takes a string array of address and returns a scrollable component for logging. The array is reversed when mapping so that when we append to the list the new element will come to the top of the log.

### CODE REVIEW

**Review by tanerdurmaz — CHANGES_REQUESTED** [review]
the component will take NFT collection address as input,
for example address of [this](https://testnets.opensea.io/assets/goerli/0x6627a33c0a232dadda91a3f78fcf9c4d98e3808b/8) collection is 0x6627a33c0a232dadda91a3f78fcf9c4d98e3808b 

with using this address you will list who were the minter addresses of the token 
like 
0xC284e4e24DeB81aEFFC8f6e1253325b2f829Fb75 minted #2 ! 
0x4bA9285EDE9D46Bc367ee1d5cD5a8F1d9e6572e6 minted  #1 !

in [here](https://goerli.etherscan.io/address/0x6627a33c0a232dadda91a3f78fcf9c4d98e3808b) you can see  the tansactions including mint events. you can use etherscan api for goerli testnet

**Comment by squal1** [comment]
Sorry for mis-understanding the task before. I made the changes and you can check it out now.

**Review by tanerdurmaz — CHANGES_REQUESTED** [review]
great update, nice to have typescript code. now need couple of small changes before merge.

lets move mintLogs.tsx into components folder. 
and lets start using it in dao.tsx and it will take contracts[0] as input. 
also make sure component handles the case contracts[0]  is undefined. 
and lets make wallet addresses short like 0x6627...808b

**Comment by squal1** [comment]
Changes are made and this is how it looks like now. The component will now catch the error when there is something wrong about the address.

Untitled

**Review by tanerdurmaz — APPROVED** [review]

**Pull request merged**
